# Common HL7 Segment Definitions
# Dictionary format: Segment [ID] -> { Field Index: Field Name }

HL7_SEGMENTS = {
    'MSH': {
        1: 'Field Separator',
        2: 'Encoding Characters',
        3: 'Sending Application',
        4: 'Sending Facility',
        5: 'Receiving Application',
        6: 'Receiving Facility',
        7: 'Date/Time of Message',
        8: 'Security',
        9: 'Message Type',
        10: 'Message Control ID',
        11: 'Processing ID',
        12: 'Version ID',
        13: 'Sequence Number',
        14: 'Continuation Pointer',
        15: 'Accept Acknowledgment Type',
        16: 'Application Acknowledgment Type',
        17: 'Country Code',
        18: 'Character Set',
        19: 'Principal Language Of Message',
    },
    'PID': {
        1: 'Set ID - PID',
        2: 'Patient ID',
        3: 'Patient Identifier List',
        4: 'Alternate Patient ID - PID',
        5: 'Patient Name',
        6: 'Mother\'s Maiden Name',
        7: 'Date/Time Of Birth',
        8: 'Administrative Sex',
        9: 'Patient Alias',
        10: 'Race',
        11: 'Patient Address',
        12: 'County Code',
        13: 'Phone Number - Home',
        14: 'Phone Number - Business',
        15: 'Primary Language',
        16: 'Marital Status',
        17: 'Religion',
        18: 'Patient Account Number',
        19: 'SSN Number - Patient',
        20: 'Driver\'s License Number - Patient',
        21: 'Mother\'s Identifier',
        22: 'Ethnic Group',
        23: 'Birth Place',
        24: 'Multiple Birth Indicator',
        25: 'Birth Order',
        26: 'Citizenship',
        27: 'Veterans Military Status',
        28: 'Nationality',
        29: 'Patient Death Date and Time',
        30: 'Patient Death Indicator',
        31: 'Identity Unknown Indicator',
        32: 'Identity Reliability Code',
        33: 'Last Update Date/Time',
        34: 'Last Update Facility',
        35: 'Taxonomic Classification Code',
        36: 'Breed Code',
        37: 'Strain',
        38: 'Production Class Code',
        39: 'Tribal Citizenship',
    },
    'PV1': {
        1: 'Set ID - PV1',
        2: 'Patient Class',
        3: 'Assigned Patient Location',
        4: 'Admission Type',
        5: 'Preadmit Number',
        6: 'Prior Patient Location',
        7: 'Attending Doctor',
        8: 'Referring Doctor',
        9: 'Consulting Doctor',
        10: 'Hospital Service',
        11: 'Temporary Location',
        12: 'Preadmit Test Indicator',
        13: 'Re-admission Indicator',
        14: 'Admit Source',
        15: 'Ambulatory Status',
        16: 'VIP Indicator',
        17: 'Admitting Doctor',
        18: 'Patient Type',
        19: 'Visit Number',
    },
    'NK1': {
        1: 'Set ID - NK1',
        2: 'Name',
        3: 'Relationship',
        4: 'Address',
        5: 'Phone Number',
        6: 'Business Phone Number',
        7: 'Contact Role',
        13: 'Organization Name - NK1',
    },
    'OBR': {
        1: 'Set ID - OBR',
        2: 'Placer Order Number',
        3: 'Filler Order Number',
        4: 'Universal Service Identifier',
        5: 'Priority',
        6: 'Requested Date/Time',
        7: 'Observation Date/Time',
        8: 'Observation End Date/Time',
        9: 'Collection Volume',
        10: 'Collector Identifier',
        11: 'Specimen Action Code',
        12: 'Danger Code',
        13: 'Relevant Clinical Information',
        14: 'Specimen Received Date/Time',
        15: 'Specimen Source',
        16: 'Ordering Provider',
        17: 'Order Callback Phone Number',
        18: 'Placer Field 1',
        19: 'Placer Field 2',
        20: 'Filler Field 1',
        21: 'Filler Field 2',
        22: 'Results Rpt/Status Chng - Date/Time',
        23: 'Charge to Practice',
        24: 'Diagnostic Serv Sect ID',
        25: 'Result Status',
        26: 'Parent Result',
        27: 'Quantity/Timing',
        28: 'Result Copies To',
        29: 'Parent Number',
        30: 'Transportation Mode',
        31: 'Reason for Study',
        32: 'Principal Result Interpreter',
        33: 'Assistant Result Interpreter',
        34: 'Technician',
        35: 'Transcriptionist',
        36: 'Scheduled Date/Time',
        37: 'Number of Sample Containers',
        38: 'Transport Logistics of Collected Sample',
        39: 'Collector\'s Comment',
        40: 'Transport Arrangement Responsibility',
        41: 'Transport Arranged',
        42: 'New OBR.20 Value',
        43: 'New OBR.21 Value',
        44: 'Relevant Clinical Information',
        45: 'Name of Diagnostic Service',
        46: 'Result Handling',
        47: 'Parent Universal Service Identifier',
        48: 'Observation Group Identifier',
        49: 'Observation Group Type',
    },
    'OBX': {
        1: 'Set ID - OBX',
        2: 'Value Type',
        3: 'Observation Identifier',
        4: 'Observation Sub-ID',
        5: 'Observation Value',
        6: 'Units',
        7: 'References Range',
        8: 'Abnormal Flags',
        11: 'Observation Result Status',
        14: 'Date/Time of the Observation',
        15: 'Producer\'s ID',
        16: 'Responsible Observer',
        17: 'Observation Method',
    },
    'ORC': {
        1: 'Order Control',
        2: 'Placer Order Number',
        3: 'Filler Order Number',
        4: 'Placer Group Number',
        5: 'Order Status',
        6: 'Response Flag',
        7: 'Quantity/Timing',
        8: 'Parent Order',
        9: 'Date/Time of Transaction',
        10: 'Entered By',
        11: 'Verified By',
        12: 'Ordering Provider',
        13: 'Enterer\'s Location',
        14: 'Call Back Phone Number',
        15: 'Order Effective Date/Time',
        16: 'Order Control Code Reason',
        17: 'Entering Organization',
        18: 'Entering Device',
        19: 'Action By',
        20: 'Advanced Beneficiary Notice Code',
        21: 'Ordering Facility Name',
        22: 'Ordering Facility Address',
        23: 'Ordering Facility Phone Number',
        24: 'Ordering Provider Address',
        25: 'Order Status Modifier',
        26: 'Advanced Beneficiary Notice Override Reason',
    },
    'AL1': {
        1: 'Set ID - AL1',
        2: 'Allergen Type Code',
        3: 'Allergen Code/Mnemonic/Description',
        4: 'Allergy Severity Code',
        5: 'Allergy Reaction Code',
    },
    'DG1': {
        1: 'Set ID - DG1',
        3: 'Diagnosis Code - DG1',
        6: 'Diagnosis Type',
        15: 'Diagnosis Priority',
        16: 'Diagnosing Clinician',
    },
    # Missing Segments Added based on User Feedback and Common Usage
    'PD1': {
        1: 'Living Dependency',
        2: 'Living Arrangement',
        3: 'Patient Primary Facility',
        4: 'Patient Primary Care Provider Name & ID No.',
        5: 'Student Indicator',
        6: 'Handicap',
        7: 'Living Will Code',
        8: 'Organ Donor Code',
        9: 'Separate Bill',
        10: 'Duplicate Patient',
        11: 'Publicity Code',
        12: 'Protection Indicator',
        13: 'Protection Indicator Effective Date',
        14: 'Place of Worship',
        15: 'Advance Directive Code',
        16: 'Immunization Registry Status',
        17: 'Immunization Registry Status Effective Date',
        18: 'Publicity Code Effective Date',
        19: 'Military Branch',
        20: 'Military Rank/Grade',
        21: 'Military Status',
    },
    'RXA': {
        1: 'Give Sub-ID Counter',
        2: 'Administration Sub-ID Counter',
        3: 'Date/Time Start of Administration',
        4: 'Date/Time End of Administration',
        5: 'Administered Code',
        6: 'Administered Amount',
        7: 'Administered Units',
        8: 'Administered Dosage Form',
        9: 'Administration Notes',
        10: 'Administering Provider',
        11: 'Administered-at Location',
        12: 'Administered Per (Time Unit)',
        13: 'Administered Strength',
        14: 'Administered Strength Units',
        15: 'Substance Lot Number',
        16: 'Substance Expiration Date',
        17: 'Substance Manufacturer Name',
        18: 'Substance/Treatment Refusal Reason',
        19: 'Indication',
        20: 'Completion Status',
        21: 'Action Code - RXA',
        22: 'System Entry Date/Time',
    },
    'IN1': {
        1: 'Set ID - IN1',
        2: 'Insurance Plan ID',
        3: 'Insurance Company ID',
        4: 'Insurance Company Name',
        5: 'Insurance Company Address',
        6: 'Insurance Co Contact Person',
        7: 'Insurance Co Phone Number',
        8: 'Group Number',
        9: 'Group Name',
        10: 'Insured\'s Group Emp ID',
        11: 'Insured\'s Group Emp Name',
        12: 'Plan Effective Date',
        13: 'Plan Expiration Date',
        36: 'Policy Number',
    },
    'GT1': {
        1: 'Set ID - GT1',
        2: 'Guarantor Number',
        3: 'Guarantor Name',
        4: 'Guarantor Spouse Name',
        5: 'Guarantor Address',
        6: 'Guarantor Ph Num - Home',
        7: 'Guarantor Ph Num - Business',
        8: 'Guarantor Date/Time Of Birth',
        9: 'Guarantor Sex',
        10: 'Guarantor Type',
        11: 'Guarantor Relationship',
        12: 'Guarantor SSN',
    },
}
